[package]
name = "sozu"
description = "sozu, a fast, reliable, hot reconfigurable HTTP reverse proxy"
repository = "https://github.com/sozu-proxy/sozu"
readme = "README.md"
documentation = "https://docs.rs/sozu"
homepage = "http://sozu.io"
version = "0.14.2"
license = "AGPL-3.0"
authors = [
  "Geoffroy Couprie <geo.couprie@gmail.com>",
  "Eloi Demolis <eloi.demolis@clever-cloud.com>",
  "Emmanuel Bosquet <emmanuel.bosquet@clever-cloud.com>",
  "Florentin Dubois <florentin.dubois@clever-cloud.com>",
]
categories = ["network-programming"]
edition="2021"
include = [
  "README.md",
  "Cargo.toml",
  "src/**/*",
]

[[bin]]
name = "sozu"

[dependencies]
acme-lib = "^0.8.2"
anyhow = "^1.0.66"
async-dup = "^1.2.2"
async-io = "^1.12.0"
clap = { version = "^4.0.29", features = ["derive"] }
futures = "^0.3.25"
futures-lite = "^1.12.0"
hex = "^0.4.3"
jemallocator = { version = "^0.5.0", optional = true }
lazy_static = "^1.4.0"
libc = "^0.2.137"
log = "^0.4.17"
mio = { version = "^0.8.5", features = ["os-poll", "net"] }
nix = "^0.26.1"
nom = "^7.1.1"
paw = "^1.0.0"
prettytable-rs = { version = "^0.9.0", default-features = false }
serde = { version = "^1.0.148", features = ["derive"] }
serde_json = "^1.0.89"
time = "^0.3.17"
tracing = "^0.1.37"
tracing-subscriber = "^0.3.16"
rand = "^0.8.5"
regex = "^1.7.0"
slab = "^0.4.7"
smol = "^1.3.0"
tiny_http = "^0.12.0"
tempfile = "^3.3.0"
termion = "^2.0.1"

sozu-command-lib = { path = "../command" }
sozu-lib = { path = "../lib" }

[target.'cfg(target_os="linux")'.dependencies]
num_cpus = "^1.13.1"

[features]
default = ["jemallocator"]
unstable = []
logs-debug = ["sozu-lib/logs-debug", "sozu-command-lib/logs-debug"]
logs-trace = ["sozu-lib/logs-trace", "sozu-command-lib/logs-trace"]
tolerant-http1-parser = ["sozu-lib/tolerant-http1-parser"]

[badges]
travis-ci = { repository = "sozu-proxy/sozu" }
